maingui.o: maingui.cc argumentsettings.h helpers.h evetime.h eveapi.h \
  asynchttp.h http.h ref_ptr.h thread.h exception.h server.h serverlist.h \
  imagestore.h gtkdefines.h gtkserver.h gtkcharpage.h apiintraining.h \
  apibase.h apicharsheet.h apiskilltree.h gtkportrait.h gtkinfodisplay.h \
  winbase.h versionchecker.h config.h conf.h guiuserdata.h \
  guiconfiguration.h gtkconfwidgets.h guiaboutdialog.h guievelauncher.h \
  maingui.h
guiuserdata.o: guiuserdata.cc gtkdefines.h exception.h apicharlist.h \
  ref_ptr.h http.h apibase.h eveapi.h asynchttp.h thread.h config.h \
  conf.h guiuserdata.h winbase.h
guiconfiguration.o: guiconfiguration.cc helpers.h gtkdefines.h \
  imagestore.h guiconfiguration.h winbase.h gtkconfwidgets.h config.h \
  conf.h ref_ptr.h
guiaboutdialog.o: guiaboutdialog.cc asynchttp.h http.h ref_ptr.h thread.h \
  exception.h defines.h gtkdefines.h imagestore.h guiaboutdialog.h \
  winbase.h
guiskill.o: guiskill.cc apiskilltree.h http.h ref_ptr.h apibase.h \
  eveapi.h asynchttp.h thread.h exception.h helpers.h gtkdefines.h \
  guiskill.h winbase.h
guiskillplanner.o: guiskillplanner.cc helpers.h imagestore.h \
  gtkportrait.h asynchttp.h http.h ref_ptr.h thread.h exception.h \
  gtkdefines.h guiskillplanner.h gtkplannerbase.h apiskilltree.h \
  apibase.h eveapi.h gtkskilldetails.h apicharsheet.h gtktrainingplan.h \
  gtkcolumnsbase.h config.h conf.h gtkconfwidgets.h apiintraining.h \
  winbase.h
guixmlsource.o: guixmlsource.cc gtkdefines.h guixmlsource.h winbase.h \
  http.h ref_ptr.h
guievelauncher.o: guievelauncher.cc gtkdefines.h exception.h helpers.h \
  bgprocess.h thread.h config.h conf.h ref_ptr.h guievelauncher.h \
  winbase.h
gtkevemon.o: gtkevemon.cc argumentsettings.h evetime.h config.h conf.h \
  ref_ptr.h serverlist.h server.h imagestore.h maingui.h gtkinfodisplay.h \
  winbase.h versionchecker.h asynchttp.h http.h thread.h exception.h \
  gtkserver.h eveapi.h
gtkserver.o: gtkserver.cc exception.h serverlist.h server.h helpers.h \
  thread.h gtkserver.h
gtkconfwidgets.o: gtkconfwidgets.cc gtkportrait.h asynchttp.h http.h \
  ref_ptr.h thread.h exception.h config.h conf.h gtkconfwidgets.h
gtkcharpage.o: gtkcharpage.cc config.h conf.h ref_ptr.h evetime.h \
  helpers.h exception.h apiintraining.h http.h apibase.h eveapi.h \
  asynchttp.h thread.h apicharsheet.h apiskilltree.h imagestore.h \
  gtkdefines.h gtkhelpers.h guiskill.h winbase.h guiskillplanner.h \
  gtkplannerbase.h gtkskilldetails.h gtktrainingplan.h gtkportrait.h \
  gtkcolumnsbase.h gtkconfwidgets.h guixmlsource.h gtkcharpage.h \
  gtkinfodisplay.h
gtkportrait.o: gtkportrait.cc http.h ref_ptr.h imagestore.h config.h \
  conf.h gtkportrait.h asynchttp.h thread.h exception.h
gtkinfodisplay.o: gtkinfodisplay.cc evetime.h exception.h gtkdefines.h \
  gtkinfodisplay.h winbase.h
gtkplannerbase.o: gtkplannerbase.cc imagestore.h helpers.h \
  gtkplannerbase.h apiskilltree.h http.h ref_ptr.h apibase.h eveapi.h \
  asynchttp.h thread.h exception.h
gtkcolumnsbase.o: gtkcolumnsbase.cc exception.h helpers.h \
  gtkcolumnsbase.h
gtkhelpers.o: gtkhelpers.cc evetime.h imagestore.h helpers.h gtkhelpers.h \
  apiskilltree.h http.h ref_ptr.h apibase.h eveapi.h asynchttp.h thread.h \
  exception.h apicharsheet.h
gtktrainingplan.o: gtktrainingplan.cc helpers.h evetime.h \
  gtkcolumnsbase.h gtkportrait.h asynchttp.h http.h ref_ptr.h thread.h \
  exception.h gtkhelpers.h apiskilltree.h apibase.h eveapi.h \
  apicharsheet.h gtkconfwidgets.h config.h conf.h gtkdefines.h \
  imagestore.h gtktrainingplan.h apiintraining.h
gtkskilldetails.o: gtkskilldetails.cc helpers.h evetime.h imagestore.h \
  gtkdefines.h gtkhelpers.h apiskilltree.h http.h ref_ptr.h apibase.h \
  eveapi.h asynchttp.h thread.h exception.h apicharsheet.h \
  gtkskilldetails.h gtkplannerbase.h
imagestore.o: imagestore.cc images/skill.h images/img_skill.h \
  images/skillstatus.h images/img_skillstatus_at0.xpm \
  images/img_skillstatus_at1.xpm images/img_skillstatus_at2.xpm \
  images/img_skillstatus_at3.xpm images/img_skillstatus_at4.xpm \
  images/img_skillstatus_at5.xpm images/img_skillstatus_havepre.xpm \
  images/img_skillstatus_nopre.xpm images/skillicons.h \
  images/img_skillicons_skill.h images/img_skillicons_group.h \
  images/img_skillicons_train.h images/img_skillicons_done.h \
  images/img_skillicons_part.h images/img_skillicons_faded.h \
  images/skillprogress.h images/img_skillprogress.xpm images/skilldeps.h \
  images/img_skilldeps_none.h images/img_skilldeps_partial.h \
  images/img_skilldeps_have.h images/skillplan.h \
  images/img_skillplan_trained.h images/img_skillplan_training.h \
  images/img_skillplan_trainable.h images/img_skillplan_untrainable.h \
  images/img_skillplan_deperror.h images/eveportrait.h \
  images/img_eveportrait.xpm images/applogo.h images/img_applogo.xpm \
  images/aboutlogo.h images/img_aboutlogo.xpm images/menuicons.h \
  images/img_menu_evemon.xpm images/img_menu_char.xpm \
  images/img_menu_help.xpm images/guiimages.h images/img_columnconf.h \
  images/img_columnconf_faded.h imagestore.h
server.o: server.cc exception.h server.h
serverlist.o: serverlist.cc config.h conf.h ref_ptr.h exception.h \
  thread.h serverlist.h server.h
helpers.o: helpers.cc helpers.h
conf.o: conf.cc exception.h conf.h ref_ptr.h
config.o: config.cc config.h conf.h ref_ptr.h
xml.o: xml.cc exception.h xml.h ref_ptr.h
evetime.o: evetime.cc evetime.h config.h conf.h ref_ptr.h
bgprocess.o: bgprocess.cc exception.h bgprocess.h thread.h
http.o: http.cc exception.h http.h ref_ptr.h
asynchttp.o: asynchttp.cc asynchttp.h http.h ref_ptr.h thread.h \
  exception.h
eveapi.o: eveapi.cc config.h conf.h ref_ptr.h eveapi.h asynchttp.h http.h \
  thread.h exception.h
versionchecker.o: versionchecker.cc config.h conf.h ref_ptr.h defines.h \
  versionchecker.h gtkinfodisplay.h winbase.h asynchttp.h http.h thread.h \
  exception.h
apibase.o: apibase.cc helpers.h evetime.h exception.h apibase.h eveapi.h \
  asynchttp.h http.h ref_ptr.h thread.h
apicharlist.o: apicharlist.cc xml.h ref_ptr.h exception.h apicharlist.h \
  http.h apibase.h eveapi.h asynchttp.h thread.h
apicharsheet.o: apicharsheet.cc exception.h helpers.h xml.h ref_ptr.h \
  apibase.h eveapi.h asynchttp.h http.h thread.h apiskilltree.h \
  apicharsheet.h
apiintraining.o: apiintraining.cc xml.h ref_ptr.h evetime.h \
  apiintraining.h http.h apibase.h eveapi.h asynchttp.h thread.h \
  exception.h
apiskilltree.o: apiskilltree.cc config.h conf.h ref_ptr.h exception.h \
  xml.h helpers.h skilltree.xml.h apiskilltree.h http.h apibase.h \
  eveapi.h asynchttp.h thread.h
argumentsettings.o: argumentsettings.cc defines.h argumentsettings.h
