CXX ?= sunCC

CORES = $(shell psrinfo -p)

GCC_FLAGS = +w +w2 -g
GTK_FLAGS = $(shell pkg-config --cflags gtkmm-2.4)
GTK_LIBS = $(shell pkg-config --libs gtkmm-2.4)
PTH_LIBS = -lpthread
SOLARIS_LIBS = -lnsl -lresolv -lsocket -lz
XML_FLAGS = $(shell pkg-config --cflags libxml-2.0)
XML_LIBS = $(shell pkg-config --libs libxml-2.0)

CXXFLAGS ?= ${GCC_FLAGS}
CXXFLAGS += ${GTK_FLAGS} ${XML_FLAGS}
LDFLAGS += ${GTK_LIBS} ${PTH_LIBS} ${SOLARIS_LIBS} ${XML_LIBS}

BINARY = gtkevemon
